# name: call date workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   call-date-workflow:
#     uses: ./.github/workflows/reusable.yaml

name: adding two numbers

on:
  push:
    branches:
      - main

jobs:
  calling-adding-workflow:
    uses: ./.github/workflows/reusable.yaml
    with:
      number01: 10
      number02: 30
