name: running the shell script
run-name: running the shell script

on:
  push:
    branches:
      - main
    paths:
      - test.sh
      - Nikhil/**
    # paths-ignore:
    #   - ignore.sh

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: run shell script
        run: |
          chmod +x ./test.sh
          ./test.sh
          chmod +x ./ignore.sh
          ./ignore.sh    
      
  

      
