name: Hello GitHub Actions

on:
  push:
    branches:
      - main
    
  workflow_dispatch:
    inputs:
        username:
          description: "enter the name"
          required: true
          
        age:
          description: "enter the age"
          required: true
          
              

jobs:
  user-input:
    runs-on: self-hosted
    
    steps:
      - name: print user inputs        
        run: |
          echo "hello this is, ${{github.event.inputs.username}}"
          echo "my age is, ${{github.event.inputs.age}} old!!"

